

apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-cli-service-account
  labels:
    app: awscli
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::226075141250:role/snd-zenith-email-sender-sqs




---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli
  labels:
    app: aws-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      name: aws-cli
      labels:
        app: aws-cli
    spec:
      serviceAccountName: aws-cli-service-account
      containers:
        - name: aws-cli
          image: ubuntu
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              aws sqs list-queues
              sleep 604800
      restartPolicy: Always
