#Globally enabling Istio mutual TLS in STRICT mode

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  mtls:
    mode: STRICT

# todo: how to enable STRICT mode only for default ns 
