
apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: rollout-ref-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: http-server-app
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: http-server-deployment-v1
  strategy:
    canary:
      canaryService: rollouts-demo-canary
      stableService: http-server-service
      trafficRouting:
        istio:
          virtualServices:
            - name: rollouts-demo-vsvc1 # At least one virtualService is required
              routes:
                - primary # At least one route is required
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { }
        - setWeight: 60
        - pause: { }
        - setWeight: 80
        - pause: { }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-deployment-v1
  labels:
    app: http-server-app
    version: v1
spec:
  selector:
    matchLabels:
      app: http-server-app
      version: v1
  replicas: 0
  template:
    metadata:
      labels:
        app: http-server-app
        version: v1
    spec:
      containers:
        - name: http-server-container
          image: mojeico/http-server:v11
          ports:
            - name: http-serv-port
              containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: http-server-service
spec:
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: http-server-app
    # This selector will be updated with the pod-template-hash of the stable ReplicaSet. e.g.:
    # rollouts-pod-template-hash: 789746c88d

---

apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-canary
spec:
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: http-server-app
    # This selector will be updated with the pod-template-hash of the canary ReplicaSet. e.g.:
    # rollouts-pod-template-hash: 7bf84f9696
