apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
    version: v1
spec:
  selector:
    matchLabels:
      app: client
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: client
        version: v1
    spec:
      containers:
        - name: client-container
          image: client-grpc:v1.4
          ports:
            - name: client-port
              containerPort: 3000
      #restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 3000
---


apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: grpc-service
spec:
  hostname: "*"
  prefix: /
  service: client-service:80       # Be explicit about port 80. THIS IS IMPORTANT: see below
  tls: istio-upstream