apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      version: v2
  template:
    metadata:
      annotations:
        prometheus.istio.io/merge-metrics: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
      labels:
        app: client
        version: v2
    spec:
      serviceAccountName: client-service-account
      containers:
        - name: client-container
          image: mojeico/client-grpc:v1
          ports:
            - name: client-port
              containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
    service: client
spec:
  selector:
    app: client
  ports:
    - port: 3000
      name: http
      #default is TCP
      appProtocol: http
      protocol: TCP
      targetPort: 3000
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-service-account
  labels:
    account: client
automountServiceAccountToken: true

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
    #app.kubernetes.io/name: edge-stack
  servers:
    - port:
        number: 80
        #number: 8080
        name: http
        protocol: HTTP
      hosts:
        - mojeico.work

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-virtual-service
spec:
  hosts:
    - mojeico.work
  gateways:
    - api-gateway
  http:
    - match:
        - uri:
            exact: /api/v1/http
      route:
        - destination:
            host: client
            port:
              number: 3000


---


apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: client
spec:
  hosts:
    - client
  http:
    - route:
        - destination:
            host: client
          weight: 100


