apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-client
  labels:
    app.kubernetesio/name: fastapi-client
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: fastapi-client
spec:
  selector:
    matchLabels:
      app.kubernetesio/name: fastapi-client
      app.kubernetes.io/version: v1
      app.kubernetes.io/instance: fastapi-client
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetesio/name: fastapi-client
        app.kubernetes.io/version: v1
        app.kubernetes.io/instance: fastapi-client
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: fastapi-client
          image: mojeico/python-client:v777
          ports:
            - name: client-port
              containerPort: 3003

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-client-service
spec:
  selector:
    app.kubernetesio/name: fastapi-client
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: fastapi-client
  ports:
    - port: 80
      targetPort: 3003

---


apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: fastapi-client-mapping
spec:
  hostname: "*"
  prefix: /test/
  service: fastapi-client-service:80       # Be explicit about port 80. THIS IS IMPORTANT: see below
  tls: istio-upstream     # Originate TLS with the mTLS certificate
