apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
  labels:
    app.kubernetesio/name: fastapi-server
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: fastapi-server
spec:
  selector:
    matchLabels:
      app.kubernetesio/name: fastapi-server
      app.kubernetes.io/version: v1
      app.kubernetes.io/instance: fastapi-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetesio/name: fastapi-server
        app.kubernetes.io/version: v1
        app.kubernetes.io/instance: fastapi-server
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: fastapi-server
          image:  mojeico/python-server:v777
          ports:
            - name: server-port
              containerPort: 3004

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-server-service
spec:
  selector:
    app.kubernetesio/name: fastapi-server
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: fastapi-server
  ports:
    - port: 80
      #default is TCP
      #appProtocol: http
      #protocol: TCP
      targetPort: 3004




