apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-server-deployment-v1
  labels:
    app: get-server
    version: v1
spec:
  selector:
    matchLabels:
      app: get-server
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: get-server
        version: v1
    spec:
      containers:
        - name: get-server-container
          image: get-server-grpc:v1
          ports:
            - name: get-server-port
              containerPort: 50052
      #restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: get-server-grpc
spec:
  selector:
    app: get-server
  ports:
    - port: 50052
      targetPort: 50052
