apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
  labels:
    app: nodejs-server
    version: v2
    # for datadog APM
    tags.datadoghq.com/env: snd
    tags.datadoghq.com/service: nodejs-server
    tags.datadoghq.com/version: v11
    # for datadog APM

spec:
  selector:
    matchLabels:
      app: nodejs-server
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-server
        version: v2
        # for datadog APM
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: snd
        tags.datadoghq.com/service: nodejs-server
        tags.datadoghq.com/version: v11
        # for datadog APM
    spec:
      containers:
        - name: nodejs-server
          image: europe-west3-docker.pkg.dev/mojeico/client/nodejs-server:v1
          ports:
            - name: server-port
              containerPort: 3001


---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-server-service
spec:
  selector:
    app: nodejs-server
  ports:
    - port: 80
      #default is TCP
      #appProtocol: http
      #protocol: TCP
      targetPort: 3001


