apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-client
  labels:
    app: nodejs-client
    version: v7
    # for datadog APM
    tags.datadoghq.com/env: snd
    tags.datadoghq.com/service: nodejs-client
    tags.datadoghq.com/version: v11
    # for datadog APM
spec:
  selector:
    matchLabels:
      app: nodejs-client
      version: v7
  replicas: 1
  template:
    metadata:
      labels:
        # for datadog APM
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: snd
        tags.datadoghq.com/service: nodejs-client
        tags.datadoghq.com/version: v11
        # for datadog APM
        app: nodejs-client
        version: v7
    spec:
      containers:
        - name: nodejs-client
          image: europe-west3-docker.pkg.dev/mojeico/client/nodejs-client:v10
          ports:
            - name: client-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-client-service
spec:
  selector:
    app: nodejs-client
  ports:
    - port: 80
      #default is TCP
      #appProtocol: http
      #protocol: TCP
      targetPort: 3000
