apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-client
  labels:
    app.kubernetesio/name: nodejs-client
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: nodejs-client
spec:
  selector:
    matchLabels:
      app.kubernetesio/name: nodejs-client
      app.kubernetes.io/version: v1
      app.kubernetes.io/instance: nodejs-client
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetesio/name: nodejs-client
        app.kubernetes.io/version: v1
        app.kubernetes.io/instance: nodejs-client
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: nodejs-client
          image: mojeico/node-js-client:v454363
          ports:
            - name: client-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-client-service
spec:
  selector:
    app.kubernetesio/name: nodejs-client
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: nodejs-client
  ports:
    - port: 80
      #default is TCP
      #appProtocol: http
      #protocol: TCP
      targetPort: 3000
