apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
  labels:
    app.kubernetesio/name: nodejs-server
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: nodejs-server
spec:
  selector:
    matchLabels:
      app.kubernetesio/name: nodejs-server
      app.kubernetes.io/version: v1
      app.kubernetes.io/instance: nodejs-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetesio/name: nodejs-server
        app.kubernetes.io/version: v1
        app.kubernetes.io/instance: nodejs-server
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: nodejs-server
          image: mojeico/nodejs-server:v666
          ports:
            - name: server-port
              containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-server-service
spec:
  selector:
    app.kubernetesio/name: nodejs-server
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: nodejs-server
  ports:
    - port: 3000
      #default is TCP
      #appProtocol: http
      #protocol: TCP
      targetPort: 3001


