
base:
  enableIstioConfigCRDs: true
global:
  autoscalingv2API: true
  caAddress: ""
  caName: ""
  configCluster: false
  defaultPodDisruptionBudget:
    enabled: true
  defaultResources:
    requests:
      cpu: 10m
  externalIstiod: false
  hub: docker.io/istio
  imagePullPolicy: ""
  imagePullSecrets: []
  istioNamespace: istio-system
  istiod:
    enableAnalysis: false
  jwtPolicy: third-party-jwt
  logAsJson: false
  logging:
    level: default:info
  meshID: ""
  meshNetworks: {}
  mountMtlsCerts: false
  multiCluster:
    clusterName: ""
    enabled: false
  network: ""
  omitSidecarInjectorConfigMap: false
  oneNamespace: false
  operatorManageWebhooks: false
  pilotCertProvider: istiod
  priorityClassName: ""
  proxy:
    autoInject: enabled
    clusterDomain: cluster.local
    componentLogLevel: misc:error
    enableCoreDump: false
    excludeIPRanges: ""
    excludeInboundPorts: ""
    excludeOutboundPorts: ""
    holdApplicationUntilProxyStarts: false
    image: proxyv2
    includeIPRanges: '*'
    includeInboundPorts: '*'
    includeOutboundPorts: ""
    logLevel: warning
    privileged: false
    readinessFailureThreshold: 30
    readinessInitialDelaySeconds: 1
    readinessPeriodSeconds: 2
    resources:
      limits:
        cpu: 2000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
    statusPort: 15020
    tracer: zipkin
  proxy_init:
    image: proxyv2
  remotePilotAddress: ""
  sds:
    token:
      aud: istio-ca
  sts:
    servicePort: 0
  tag: 1.16.2
  tracer:
    datadog:
      address: $(HOST_IP):8126
    lightstep:
      accessToken: ""
      address: ""
    stackdriver:
      debug: false
      maxNumberOfAnnotations: 200
      maxNumberOfAttributes: 200
      maxNumberOfMessageEvents: 200
    zipkin:
      #address: ""
      #address: "$(HOST_IP):9411"
      #address: "jaeger-collector.default:9411"
      address: "jaeger-collector:9411"

  useMCP: false
  variant: ""
istiodRemote:
  injectionPath: /inject
  injectionURL: ""
meshConfig:
  enablePrometheusMerge: true
  rootNamespace: null
  trustDomain: cluster.local
ownerName: ""
pilot:
  autoscaleEnabled: true
  autoscaleMax: 5
  autoscaleMin: 1
  configMap: true
  configSource:
    subscribedResources: []
  cpu:
    targetAverageUtilization: 80
  deploymentLabels: {}
  enableProtocolSniffingForInbound: true
  enableProtocolSniffingForOutbound: true
  env: {}
  hub: ""
  image: pilot
  jwksResolverExtraRootCA: ""
  keepaliveMaxServerConnectionAge: 30m
  nodeSelector: {}
  plugins: []
  podAnnotations: {}
  podLabels: {}
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi
  rollingMaxSurge: 100%
  rollingMaxUnavailable: 25%
  seccompProfile: {}
  serviceAnnotations: {}
  tag: ""
  traceSampling: 1
  variant: ""
revision: ""
revisionTags: []
sidecarInjectorWebhook:
  alwaysInjectSelector: []
  defaultTemplates: []
  enableNamespacesByDefault: false
  injectedAnnotations: {}
  neverInjectSelector: []
  rewriteAppHTTPProbe: true
  templates: {}
telemetry:
  enabled: true
  v2:
    accessLogPolicy:
      enabled: false
      logWindowDuration: 43200s
    enabled: true
    metadataExchange:
      wasmEnabled: false
    prometheus:
      configOverride:
        gateway: {}
        inboundSidecar: {}
        outboundSidecar: {}
      enabled: true
      wasmEnabled: false
    stackdriver:
      configOverride: {}
      disableOutbound: false
      enabled: false
      logging: false
      monitoring: false
      topology: false