provisionDataStore:
  cassandra: false

allInOne:
  enabled: true
  image: jaegertracing/all-in-one
  tag: 1.37.0
  pullPolicy: IfNotPresent
  extraEnv: []

  # resources:
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi
  #   requests:
  #     cpu: 256m
  #     memory: 128Mi

ingester:
  enabled: false
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
spark:
  enabled: false
esRollover:
  enabled: false
esLookback:
  enabled: false
hotrod:
  enabled: false
