apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-get-server-deployment
  labels:
    app.kubernetesio/name: get-server
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: get-server
spec:
  selector:
    matchLabels:
      app.kubernetesio/name: get-server
      app.kubernetes.io/version: v1
      app.kubernetes.io/instance: get-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetesio/name: get-server
        app.kubernetes.io/version: v1
        app.kubernetes.io/instance: get-server
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: golang-get-grpc-server-service-account
      containers:
        - name: service-container
          #image: server-grpc:v1
          image: mojeico/golang-get-server:v1
          ports:
            - name: server-port
              containerPort: 50052


---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: golang-get-grpc-server-service-account
  labels:
    app.kubernetesio/name: server
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: server
automountServiceAccountToken: true


---
apiVersion: v1
kind: Service
metadata:
  name: golang-get-server-grpc
  labels:
    app.kubernetesio/name: get-server
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: get-server
spec:
  selector:
    app.kubernetesio/name: get-server
    app.kubernetes.io/version: v1
    app.kubernetes.io/instance: get-server
  ports:
    - port: 50052
      targetPort: 50052
      name: tcp
